// Code generated by mockery. DO NOT EDIT.

package container

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockLifecycle is an autogenerated mock type for the Lifecycle type
type MockLifecycle struct {
	mock.Mock
}

type MockLifecycle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLifecycle) EXPECT() *MockLifecycle_Expecter { _ = "STUB: not implemented"; return nil }

// KillContainer provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockLifecycle) KillContainer(_a0 context.Context, _a1 *Container, _a2 string, _a3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockLifecycle_KillContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillContainer'
type MockLifecycle_KillContainer_Call struct {
	*mock.Call
}

// KillContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 string
//   - _a3 bool
func (_e *MockLifecycle_Expecter) KillContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockLifecycle_KillContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_KillContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 string, _a3 bool)) *MockLifecycle_KillContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_KillContainer_Call) Return(_a0 error) *MockLifecycle_KillContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_KillContainer_Call) RunAndReturn(run func(context.Context, *Container, string, bool) error) *MockLifecycle_KillContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// PauseContainer provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockLifecycle) PauseContainer(_a0 context.Context, _a1 *Container, _a2 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockLifecycle_PauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseContainer'
type MockLifecycle_PauseContainer_Call struct {
	*mock.Call
}

// PauseContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 bool
func (_e *MockLifecycle_Expecter) PauseContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockLifecycle_PauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_PauseContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 bool)) *MockLifecycle_PauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_PauseContainer_Call) Return(_a0 error) *MockLifecycle_PauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_PauseContainer_Call) RunAndReturn(run func(context.Context, *Container, bool) error) *MockLifecycle_PauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveContainer provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockLifecycle) RemoveContainer(_a0 context.Context, _a1 *Container, _a2 RemoveOpts) error {
	_ = "STUB: not implemented"
	return nil
}

// MockLifecycle_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockLifecycle_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 RemoveOpts
func (_e *MockLifecycle_Expecter) RemoveContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockLifecycle_RemoveContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_RemoveContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 RemoveOpts)) *MockLifecycle_RemoveContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_RemoveContainer_Call) Return(_a0 error) *MockLifecycle_RemoveContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_RemoveContainer_Call) RunAndReturn(run func(context.Context, *Container, RemoveOpts) error) *MockLifecycle_RemoveContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// RestartContainer provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockLifecycle) RestartContainer(_a0 context.Context, _a1 *Container, _a2 time.Duration, _a3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockLifecycle_RestartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartContainer'
type MockLifecycle_RestartContainer_Call struct {
	*mock.Call
}

// RestartContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 time.Duration
//   - _a3 bool
func (_e *MockLifecycle_Expecter) RestartContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockLifecycle_RestartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_RestartContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 time.Duration, _a3 bool)) *MockLifecycle_RestartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_RestartContainer_Call) Return(_a0 error) *MockLifecycle_RestartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_RestartContainer_Call) RunAndReturn(run func(context.Context, *Container, time.Duration, bool) error) *MockLifecycle_RestartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StartContainer provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockLifecycle) StartContainer(_a0 context.Context, _a1 *Container, _a2 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockLifecycle_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockLifecycle_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 bool
func (_e *MockLifecycle_Expecter) StartContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockLifecycle_StartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StartContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 bool)) *MockLifecycle_StartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StartContainer_Call) Return(_a0 error) *MockLifecycle_StartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StartContainer_Call) RunAndReturn(run func(context.Context, *Container, bool) error) *MockLifecycle_StartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StopContainer provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockLifecycle) StopContainer(_a0 context.Context, _a1 *Container, _a2 int, _a3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockLifecycle_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockLifecycle_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 int
//   - _a3 bool
func (_e *MockLifecycle_Expecter) StopContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockLifecycle_StopContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StopContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 int, _a3 bool)) *MockLifecycle_StopContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StopContainer_Call) Return(_a0 error) *MockLifecycle_StopContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StopContainer_Call) RunAndReturn(run func(context.Context, *Container, int, bool) error) *MockLifecycle_StopContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StopContainerWithID provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockLifecycle) StopContainerWithID(_a0 context.Context, _a1 string, _a2 time.Duration, _a3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockLifecycle_StopContainerWithID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainerWithID'
type MockLifecycle_StopContainerWithID_Call struct {
	*mock.Call
}

// StopContainerWithID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 time.Duration
//   - _a3 bool
func (_e *MockLifecycle_Expecter) StopContainerWithID(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockLifecycle_StopContainerWithID_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StopContainerWithID_Call) Run(run func(_a0 context.Context, _a1 string, _a2 time.Duration, _a3 bool)) *MockLifecycle_StopContainerWithID_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StopContainerWithID_Call) Return(_a0 error) *MockLifecycle_StopContainerWithID_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_StopContainerWithID_Call) RunAndReturn(run func(context.Context, string, time.Duration, bool) error) *MockLifecycle_StopContainerWithID_Call {
	_ = "STUB: not implemented"
	return nil
}

// UnpauseContainer provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockLifecycle) UnpauseContainer(_a0 context.Context, _a1 *Container, _a2 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockLifecycle_UnpauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpauseContainer'
type MockLifecycle_UnpauseContainer_Call struct {
	*mock.Call
}

// UnpauseContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 bool
func (_e *MockLifecycle_Expecter) UnpauseContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockLifecycle_UnpauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_UnpauseContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 bool)) *MockLifecycle_UnpauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_UnpauseContainer_Call) Return(_a0 error) *MockLifecycle_UnpauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLifecycle_UnpauseContainer_Call) RunAndReturn(run func(context.Context, *Container, bool) error) *MockLifecycle_UnpauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockLifecycle creates a new instance of MockLifecycle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLifecycle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLifecycle {
	_ = "STUB: not implemented"
	return nil
}
