// Code generated by mockery. DO NOT EDIT.

package container

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStressor is an autogenerated mock type for the Stressor type
type MockStressor struct {
	mock.Mock
}

type MockStressor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStressor) EXPECT() *MockStressor_Expecter { _ = "STUB: not implemented"; return nil }

// StressContainer provides a mock function with given fields: _a0, _a1
func (_m *MockStressor) StressContainer(_a0 context.Context, _a1 *StressRequest) (*StressResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MockStressor_StressContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StressContainer'
type MockStressor_StressContainer_Call struct {
	*mock.Call
}

// StressContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *StressRequest
func (_e *MockStressor_Expecter) StressContainer(_a0 interface{}, _a1 interface{}) *MockStressor_StressContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStressor_StressContainer_Call) Run(run func(_a0 context.Context, _a1 *StressRequest)) *MockStressor_StressContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStressor_StressContainer_Call) Return(_a0 *StressResult, _a1 error) *MockStressor_StressContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockStressor_StressContainer_Call) RunAndReturn(run func(context.Context, *StressRequest) (*StressResult, error)) *MockStressor_StressContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockStressor creates a new instance of MockStressor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStressor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStressor {
	_ = "STUB: not implemented"
	return nil
}
