// Code generated by mockery. DO NOT EDIT.

package container

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockIPTables is an autogenerated mock type for the IPTables type
type MockIPTables struct {
	mock.Mock
}

type MockIPTables_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPTables) EXPECT() *MockIPTables_Expecter { _ = "STUB: not implemented"; return nil }

// IPTablesContainer provides a mock function with given fields: _a0, _a1
func (_m *MockIPTables) IPTablesContainer(_a0 context.Context, _a1 *IPTablesRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// MockIPTables_IPTablesContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPTablesContainer'
type MockIPTables_IPTablesContainer_Call struct {
	*mock.Call
}

// IPTablesContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *IPTablesRequest
func (_e *MockIPTables_Expecter) IPTablesContainer(_a0 interface{}, _a1 interface{}) *MockIPTables_IPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockIPTables_IPTablesContainer_Call) Run(run func(_a0 context.Context, _a1 *IPTablesRequest)) *MockIPTables_IPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockIPTables_IPTablesContainer_Call) Return(_a0 error) *MockIPTables_IPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockIPTables_IPTablesContainer_Call) RunAndReturn(run func(context.Context, *IPTablesRequest) error) *MockIPTables_IPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StopIPTablesContainer provides a mock function with given fields: _a0, _a1
func (_m *MockIPTables) StopIPTablesContainer(_a0 context.Context, _a1 *IPTablesRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// MockIPTables_StopIPTablesContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopIPTablesContainer'
type MockIPTables_StopIPTablesContainer_Call struct {
	*mock.Call
}

// StopIPTablesContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *IPTablesRequest
func (_e *MockIPTables_Expecter) StopIPTablesContainer(_a0 interface{}, _a1 interface{}) *MockIPTables_StopIPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockIPTables_StopIPTablesContainer_Call) Run(run func(_a0 context.Context, _a1 *IPTablesRequest)) *MockIPTables_StopIPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockIPTables_StopIPTablesContainer_Call) Return(_a0 error) *MockIPTables_StopIPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockIPTables_StopIPTablesContainer_Call) RunAndReturn(run func(context.Context, *IPTablesRequest) error) *MockIPTables_StopIPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockIPTables creates a new instance of MockIPTables. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPTables(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPTables {
	_ = "STUB: not implemented"
	return nil
}
