// Code generated by mockery. DO NOT EDIT.

package container

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLister is an autogenerated mock type for the Lister type
type MockLister struct {
	mock.Mock
}

type MockLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLister) EXPECT() *MockLister_Expecter { _ = "STUB: not implemented"; return nil }

// ListContainers provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockLister) ListContainers(_a0 context.Context, _a1 FilterFunc, _a2 ListOpts) ([]*Container, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MockLister_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockLister_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 FilterFunc
//   - _a2 ListOpts
func (_e *MockLister_Expecter) ListContainers(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockLister_ListContainers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLister_ListContainers_Call) Run(run func(_a0 context.Context, _a1 FilterFunc, _a2 ListOpts)) *MockLister_ListContainers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLister_ListContainers_Call) Return(_a0 []*Container, _a1 error) *MockLister_ListContainers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockLister_ListContainers_Call) RunAndReturn(run func(context.Context, FilterFunc, ListOpts) ([]*Container, error)) *MockLister_ListContainers_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockLister creates a new instance of MockLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLister {
	_ = "STUB: not implemented"
	return nil
}
