// Code generated by mockery. DO NOT EDIT.

package container

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter { _ = "STUB: not implemented"; return nil }

// Close provides a mock function with no fields
func (_m *MockClient) Close() error { _ = "STUB: not implemented"; return nil }

// MockClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockClient_Expecter) Close() *MockClient_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_Close_Call) Run(run func()) *MockClient_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_Close_Call) Return(_a0 error) *MockClient_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_Close_Call) RunAndReturn(run func() error) *MockClient_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

// ExecContainer provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *MockClient) ExecContainer(_a0 context.Context, _a1 *Container, _a2 string, _a3 []string, _a4 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_ExecContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecContainer'
type MockClient_ExecContainer_Call struct {
	*mock.Call
}

// ExecContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 string
//   - _a3 []string
//   - _a4 bool
func (_e *MockClient_Expecter) ExecContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}, _a4 interface{}) *MockClient_ExecContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_ExecContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 string, _a3 []string, _a4 bool)) *MockClient_ExecContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_ExecContainer_Call) Return(_a0 error) *MockClient_ExecContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_ExecContainer_Call) RunAndReturn(run func(context.Context, *Container, string, []string, bool) error) *MockClient_ExecContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// IPTablesContainer provides a mock function with given fields: _a0, _a1
func (_m *MockClient) IPTablesContainer(_a0 context.Context, _a1 *IPTablesRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_IPTablesContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPTablesContainer'
type MockClient_IPTablesContainer_Call struct {
	*mock.Call
}

// IPTablesContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *IPTablesRequest
func (_e *MockClient_Expecter) IPTablesContainer(_a0 interface{}, _a1 interface{}) *MockClient_IPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_IPTablesContainer_Call) Run(run func(_a0 context.Context, _a1 *IPTablesRequest)) *MockClient_IPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_IPTablesContainer_Call) Return(_a0 error) *MockClient_IPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_IPTablesContainer_Call) RunAndReturn(run func(context.Context, *IPTablesRequest) error) *MockClient_IPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// KillContainer provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockClient) KillContainer(_a0 context.Context, _a1 *Container, _a2 string, _a3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_KillContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KillContainer'
type MockClient_KillContainer_Call struct {
	*mock.Call
}

// KillContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 string
//   - _a3 bool
func (_e *MockClient_Expecter) KillContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockClient_KillContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_KillContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 string, _a3 bool)) *MockClient_KillContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_KillContainer_Call) Return(_a0 error) *MockClient_KillContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_KillContainer_Call) RunAndReturn(run func(context.Context, *Container, string, bool) error) *MockClient_KillContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// ListContainers provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockClient) ListContainers(_a0 context.Context, _a1 FilterFunc, _a2 ListOpts) ([]*Container, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MockClient_ListContainers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListContainers'
type MockClient_ListContainers_Call struct {
	*mock.Call
}

// ListContainers is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 FilterFunc
//   - _a2 ListOpts
func (_e *MockClient_Expecter) ListContainers(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockClient_ListContainers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_ListContainers_Call) Run(run func(_a0 context.Context, _a1 FilterFunc, _a2 ListOpts)) *MockClient_ListContainers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_ListContainers_Call) Return(_a0 []*Container, _a1 error) *MockClient_ListContainers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_ListContainers_Call) RunAndReturn(run func(context.Context, FilterFunc, ListOpts) ([]*Container, error)) *MockClient_ListContainers_Call {
	_ = "STUB: not implemented"
	return nil
}

// NetemContainer provides a mock function with given fields: _a0, _a1
func (_m *MockClient) NetemContainer(_a0 context.Context, _a1 *NetemRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_NetemContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NetemContainer'
type MockClient_NetemContainer_Call struct {
	*mock.Call
}

// NetemContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *NetemRequest
func (_e *MockClient_Expecter) NetemContainer(_a0 interface{}, _a1 interface{}) *MockClient_NetemContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_NetemContainer_Call) Run(run func(_a0 context.Context, _a1 *NetemRequest)) *MockClient_NetemContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_NetemContainer_Call) Return(_a0 error) *MockClient_NetemContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_NetemContainer_Call) RunAndReturn(run func(context.Context, *NetemRequest) error) *MockClient_NetemContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// PauseContainer provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockClient) PauseContainer(_a0 context.Context, _a1 *Container, _a2 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_PauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PauseContainer'
type MockClient_PauseContainer_Call struct {
	*mock.Call
}

// PauseContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 bool
func (_e *MockClient_Expecter) PauseContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockClient_PauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_PauseContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 bool)) *MockClient_PauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_PauseContainer_Call) Return(_a0 error) *MockClient_PauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_PauseContainer_Call) RunAndReturn(run func(context.Context, *Container, bool) error) *MockClient_PauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// RemoveContainer provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockClient) RemoveContainer(_a0 context.Context, _a1 *Container, _a2 RemoveOpts) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_RemoveContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveContainer'
type MockClient_RemoveContainer_Call struct {
	*mock.Call
}

// RemoveContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 RemoveOpts
func (_e *MockClient_Expecter) RemoveContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockClient_RemoveContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_RemoveContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 RemoveOpts)) *MockClient_RemoveContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_RemoveContainer_Call) Return(_a0 error) *MockClient_RemoveContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_RemoveContainer_Call) RunAndReturn(run func(context.Context, *Container, RemoveOpts) error) *MockClient_RemoveContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// RestartContainer provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockClient) RestartContainer(_a0 context.Context, _a1 *Container, _a2 time.Duration, _a3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_RestartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartContainer'
type MockClient_RestartContainer_Call struct {
	*mock.Call
}

// RestartContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 time.Duration
//   - _a3 bool
func (_e *MockClient_Expecter) RestartContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockClient_RestartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_RestartContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 time.Duration, _a3 bool)) *MockClient_RestartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_RestartContainer_Call) Return(_a0 error) *MockClient_RestartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_RestartContainer_Call) RunAndReturn(run func(context.Context, *Container, time.Duration, bool) error) *MockClient_RestartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StartContainer provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockClient) StartContainer(_a0 context.Context, _a1 *Container, _a2 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_StartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartContainer'
type MockClient_StartContainer_Call struct {
	*mock.Call
}

// StartContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 bool
func (_e *MockClient_Expecter) StartContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockClient_StartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StartContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 bool)) *MockClient_StartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StartContainer_Call) Return(_a0 error) *MockClient_StartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StartContainer_Call) RunAndReturn(run func(context.Context, *Container, bool) error) *MockClient_StartContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StopContainer provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockClient) StopContainer(_a0 context.Context, _a1 *Container, _a2 int, _a3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_StopContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainer'
type MockClient_StopContainer_Call struct {
	*mock.Call
}

// StopContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 int
//   - _a3 bool
func (_e *MockClient_Expecter) StopContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockClient_StopContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 int, _a3 bool)) *MockClient_StopContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopContainer_Call) Return(_a0 error) *MockClient_StopContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopContainer_Call) RunAndReturn(run func(context.Context, *Container, int, bool) error) *MockClient_StopContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StopContainerWithID provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *MockClient) StopContainerWithID(_a0 context.Context, _a1 string, _a2 time.Duration, _a3 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_StopContainerWithID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopContainerWithID'
type MockClient_StopContainerWithID_Call struct {
	*mock.Call
}

// StopContainerWithID is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 string
//   - _a2 time.Duration
//   - _a3 bool
func (_e *MockClient_Expecter) StopContainerWithID(_a0 interface{}, _a1 interface{}, _a2 interface{}, _a3 interface{}) *MockClient_StopContainerWithID_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopContainerWithID_Call) Run(run func(_a0 context.Context, _a1 string, _a2 time.Duration, _a3 bool)) *MockClient_StopContainerWithID_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopContainerWithID_Call) Return(_a0 error) *MockClient_StopContainerWithID_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopContainerWithID_Call) RunAndReturn(run func(context.Context, string, time.Duration, bool) error) *MockClient_StopContainerWithID_Call {
	_ = "STUB: not implemented"
	return nil
}

// StopIPTablesContainer provides a mock function with given fields: _a0, _a1
func (_m *MockClient) StopIPTablesContainer(_a0 context.Context, _a1 *IPTablesRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_StopIPTablesContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopIPTablesContainer'
type MockClient_StopIPTablesContainer_Call struct {
	*mock.Call
}

// StopIPTablesContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *IPTablesRequest
func (_e *MockClient_Expecter) StopIPTablesContainer(_a0 interface{}, _a1 interface{}) *MockClient_StopIPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopIPTablesContainer_Call) Run(run func(_a0 context.Context, _a1 *IPTablesRequest)) *MockClient_StopIPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopIPTablesContainer_Call) Return(_a0 error) *MockClient_StopIPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopIPTablesContainer_Call) RunAndReturn(run func(context.Context, *IPTablesRequest) error) *MockClient_StopIPTablesContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StopNetemContainer provides a mock function with given fields: _a0, _a1
func (_m *MockClient) StopNetemContainer(_a0 context.Context, _a1 *NetemRequest) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_StopNetemContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopNetemContainer'
type MockClient_StopNetemContainer_Call struct {
	*mock.Call
}

// StopNetemContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *NetemRequest
func (_e *MockClient_Expecter) StopNetemContainer(_a0 interface{}, _a1 interface{}) *MockClient_StopNetemContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopNetemContainer_Call) Run(run func(_a0 context.Context, _a1 *NetemRequest)) *MockClient_StopNetemContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopNetemContainer_Call) Return(_a0 error) *MockClient_StopNetemContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StopNetemContainer_Call) RunAndReturn(run func(context.Context, *NetemRequest) error) *MockClient_StopNetemContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// StressContainer provides a mock function with given fields: _a0, _a1
func (_m *MockClient) StressContainer(_a0 context.Context, _a1 *StressRequest) (*StressResult, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MockClient_StressContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StressContainer'
type MockClient_StressContainer_Call struct {
	*mock.Call
}

// StressContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *StressRequest
func (_e *MockClient_Expecter) StressContainer(_a0 interface{}, _a1 interface{}) *MockClient_StressContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StressContainer_Call) Run(run func(_a0 context.Context, _a1 *StressRequest)) *MockClient_StressContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StressContainer_Call) Return(_a0 *StressResult, _a1 error) *MockClient_StressContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_StressContainer_Call) RunAndReturn(run func(context.Context, *StressRequest) (*StressResult, error)) *MockClient_StressContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// UnpauseContainer provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockClient) UnpauseContainer(_a0 context.Context, _a1 *Container, _a2 bool) error {
	_ = "STUB: not implemented"
	return nil
}

// MockClient_UnpauseContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnpauseContainer'
type MockClient_UnpauseContainer_Call struct {
	*mock.Call
}

// UnpauseContainer is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *Container
//   - _a2 bool
func (_e *MockClient_Expecter) UnpauseContainer(_a0 interface{}, _a1 interface{}, _a2 interface{}) *MockClient_UnpauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_UnpauseContainer_Call) Run(run func(_a0 context.Context, _a1 *Container, _a2 bool)) *MockClient_UnpauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_UnpauseContainer_Call) Return(_a0 error) *MockClient_UnpauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockClient_UnpauseContainer_Call) RunAndReturn(run func(context.Context, *Container, bool) error) *MockClient_UnpauseContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	_ = "STUB: not implemented"
	return nil
}
