// Code generated by mockery. DO NOT EDIT.

package container

import mock "github.com/stretchr/testify/mock"

// MockFilterFunc is an autogenerated mock type for the FilterFunc type
type MockFilterFunc struct {
	mock.Mock
}

type MockFilterFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilterFunc) EXPECT() *MockFilterFunc_Expecter { _ = "STUB: not implemented"; return nil }

// Execute provides a mock function with given fields: _a0
func (_m *MockFilterFunc) Execute(_a0 *Container) bool { _ = "STUB: not implemented"; return false }

// MockFilterFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFilterFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *Container
func (_e *MockFilterFunc_Expecter) Execute(_a0 interface{}) *MockFilterFunc_Execute_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockFilterFunc_Execute_Call) Run(run func(_a0 *Container)) *MockFilterFunc_Execute_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockFilterFunc_Execute_Call) Return(_a0 bool) *MockFilterFunc_Execute_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockFilterFunc_Execute_Call) RunAndReturn(run func(*Container) bool) *MockFilterFunc_Execute_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockFilterFunc creates a new instance of MockFilterFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilterFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilterFunc {
	_ = "STUB: not implemented"
	return nil
}
