// Code generated by mockery v2.1.0. DO NOT EDIT.

package docker

import (
	net "net"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// mockConn is an autogenerated mock type for the conn type
type mockConn struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *mockConn) Close() error { _ = "STUB: not implemented"; return nil }

// LocalAddr provides a mock function with given fields:
func (_m *mockConn) LocalAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// Read provides a mock function with given fields: b
func (_m *mockConn) Read(b []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }

// RemoteAddr provides a mock function with given fields:
func (_m *mockConn) RemoteAddr() net.Addr { _ = "STUB: not implemented"; return *new(net.Addr) }

// SetDeadline provides a mock function with given fields: t
func (_m *mockConn) SetDeadline(t time.Time) error { _ = "STUB: not implemented"; return nil }

// SetReadDeadline provides a mock function with given fields: t
func (_m *mockConn) SetReadDeadline(t time.Time) error { _ = "STUB: not implemented"; return nil }

// SetWriteDeadline provides a mock function with given fields: t
func (_m *mockConn) SetWriteDeadline(t time.Time) error { _ = "STUB: not implemented"; return nil }

// Write provides a mock function with given fields: b
func (_m *mockConn) Write(b []byte) (int, error) { _ = "STUB: not implemented"; return 0, nil }
