// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Command is an autogenerated mock type for the Command type
type Command struct {
	mock.Mock
}

type Command_Expecter struct {
	mock *mock.Mock
}

func (_m *Command) EXPECT() *Command_Expecter { _ = "STUB: not implemented"; return nil }

// Run provides a mock function with given fields: ctx, random
func (_m *Command) Run(ctx context.Context, random bool) error {
	_ = "STUB: not implemented"
	return nil
}

// Command_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Command_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - random bool
func (_e *Command_Expecter) Run(ctx interface{}, random interface{}) *Command_Run_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Command_Run_Call) Run(run func(ctx context.Context, random bool)) *Command_Run_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Command_Run_Call) Return(_a0 error) *Command_Run_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *Command_Run_Call) RunAndReturn(run func(context.Context, bool) error) *Command_Run_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewCommand creates a new instance of Command. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *Command {
	_ = "STUB: not implemented"
	return nil
}
