// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	container "github.com/docker/docker/api/types/container"

	filters "github.com/docker/docker/api/types/filters"

	io "io"

	mock "github.com/stretchr/testify/mock"

	network "github.com/docker/docker/api/types/network"

	types "github.com/docker/docker/api/types"

	v1 "github.com/opencontainers/image-spec/specs-go/v1"
)

// ContainerAPIClient is an autogenerated mock type for the ContainerAPIClient type
type ContainerAPIClient struct {
	mock.Mock
}

type ContainerAPIClient_Expecter struct {
	mock *mock.Mock
}

func (_m *ContainerAPIClient) EXPECT() *ContainerAPIClient_Expecter {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAttach provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerAttach(ctx context.Context, _a1 string, options container.AttachOptions) (types.HijackedResponse, error) {
	_ = "STUB: not implemented"
	return *new(types.HijackedResponse), nil
}

// ContainerAPIClient_ContainerAttach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerAttach'
type ContainerAPIClient_ContainerAttach_Call struct {
	*mock.Call
}

// ContainerAttach is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.AttachOptions
func (_e *ContainerAPIClient_Expecter) ContainerAttach(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerAttach_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerAttach_Call) Run(run func(ctx context.Context, _a1 string, options container.AttachOptions)) *ContainerAPIClient_ContainerAttach_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerAttach_Call) Return(_a0 types.HijackedResponse, _a1 error) *ContainerAPIClient_ContainerAttach_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerAttach_Call) RunAndReturn(run func(context.Context, string, container.AttachOptions) (types.HijackedResponse, error)) *ContainerAPIClient_ContainerAttach_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerCommit provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerCommit(ctx context.Context, _a1 string, options container.CommitOptions) (container.CommitResponse, error) {
	_ = "STUB: not implemented"
	return *new(container.CommitResponse), nil
}

// ContainerAPIClient_ContainerCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerCommit'
type ContainerAPIClient_ContainerCommit_Call struct {
	*mock.Call
}

// ContainerCommit is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.CommitOptions
func (_e *ContainerAPIClient_Expecter) ContainerCommit(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerCommit_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerCommit_Call) Run(run func(ctx context.Context, _a1 string, options container.CommitOptions)) *ContainerAPIClient_ContainerCommit_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerCommit_Call) Return(_a0 container.CommitResponse, _a1 error) *ContainerAPIClient_ContainerCommit_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerCommit_Call) RunAndReturn(run func(context.Context, string, container.CommitOptions) (container.CommitResponse, error)) *ContainerAPIClient_ContainerCommit_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerCreate provides a mock function with given fields: ctx, config, hostConfig, networkingConfig, platform, containerName
func (_m *ContainerAPIClient) ContainerCreate(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, containerName string) (container.CreateResponse, error) {
	_ = "STUB: not implemented"
	return *new(container.CreateResponse), nil
}

// ContainerAPIClient_ContainerCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerCreate'
type ContainerAPIClient_ContainerCreate_Call struct {
	*mock.Call
}

// ContainerCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - config *container.Config
//   - hostConfig *container.HostConfig
//   - networkingConfig *network.NetworkingConfig
//   - platform *v1.Platform
//   - containerName string
func (_e *ContainerAPIClient_Expecter) ContainerCreate(ctx interface{}, config interface{}, hostConfig interface{}, networkingConfig interface{}, platform interface{}, containerName interface{}) *ContainerAPIClient_ContainerCreate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerCreate_Call) Run(run func(ctx context.Context, config *container.Config, hostConfig *container.HostConfig, networkingConfig *network.NetworkingConfig, platform *v1.Platform, containerName string)) *ContainerAPIClient_ContainerCreate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerCreate_Call) Return(_a0 container.CreateResponse, _a1 error) *ContainerAPIClient_ContainerCreate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerCreate_Call) RunAndReturn(run func(context.Context, *container.Config, *container.HostConfig, *network.NetworkingConfig, *v1.Platform, string) (container.CreateResponse, error)) *ContainerAPIClient_ContainerCreate_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerDiff provides a mock function with given fields: ctx, _a1
func (_m *ContainerAPIClient) ContainerDiff(ctx context.Context, _a1 string) ([]container.FilesystemChange, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ContainerAPIClient_ContainerDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerDiff'
type ContainerAPIClient_ContainerDiff_Call struct {
	*mock.Call
}

// ContainerDiff is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
func (_e *ContainerAPIClient_Expecter) ContainerDiff(ctx interface{}, _a1 interface{}) *ContainerAPIClient_ContainerDiff_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerDiff_Call) Run(run func(ctx context.Context, _a1 string)) *ContainerAPIClient_ContainerDiff_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerDiff_Call) Return(_a0 []container.FilesystemChange, _a1 error) *ContainerAPIClient_ContainerDiff_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerDiff_Call) RunAndReturn(run func(context.Context, string) ([]container.FilesystemChange, error)) *ContainerAPIClient_ContainerDiff_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerExecAttach provides a mock function with given fields: ctx, execID, options
func (_m *ContainerAPIClient) ContainerExecAttach(ctx context.Context, execID string, options container.ExecAttachOptions) (types.HijackedResponse, error) {
	_ = "STUB: not implemented"
	return *new(types.HijackedResponse), nil
}

// ContainerAPIClient_ContainerExecAttach_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerExecAttach'
type ContainerAPIClient_ContainerExecAttach_Call struct {
	*mock.Call
}

// ContainerExecAttach is a helper method to define mock.On call
//   - ctx context.Context
//   - execID string
//   - options container.ExecAttachOptions
func (_e *ContainerAPIClient_Expecter) ContainerExecAttach(ctx interface{}, execID interface{}, options interface{}) *ContainerAPIClient_ContainerExecAttach_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecAttach_Call) Run(run func(ctx context.Context, execID string, options container.ExecAttachOptions)) *ContainerAPIClient_ContainerExecAttach_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecAttach_Call) Return(_a0 types.HijackedResponse, _a1 error) *ContainerAPIClient_ContainerExecAttach_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecAttach_Call) RunAndReturn(run func(context.Context, string, container.ExecAttachOptions) (types.HijackedResponse, error)) *ContainerAPIClient_ContainerExecAttach_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerExecCreate provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerExecCreate(ctx context.Context, _a1 string, options container.ExecOptions) (container.ExecCreateResponse, error) {
	_ = "STUB: not implemented"
	return *new(container.ExecCreateResponse), nil
}

// ContainerAPIClient_ContainerExecCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerExecCreate'
type ContainerAPIClient_ContainerExecCreate_Call struct {
	*mock.Call
}

// ContainerExecCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.ExecOptions
func (_e *ContainerAPIClient_Expecter) ContainerExecCreate(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerExecCreate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecCreate_Call) Run(run func(ctx context.Context, _a1 string, options container.ExecOptions)) *ContainerAPIClient_ContainerExecCreate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecCreate_Call) Return(_a0 container.ExecCreateResponse, _a1 error) *ContainerAPIClient_ContainerExecCreate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecCreate_Call) RunAndReturn(run func(context.Context, string, container.ExecOptions) (container.ExecCreateResponse, error)) *ContainerAPIClient_ContainerExecCreate_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerExecInspect provides a mock function with given fields: ctx, execID
func (_m *ContainerAPIClient) ContainerExecInspect(ctx context.Context, execID string) (container.ExecInspect, error) {
	_ = "STUB: not implemented"
	return *new(container.ExecInspect), nil
}

// ContainerAPIClient_ContainerExecInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerExecInspect'
type ContainerAPIClient_ContainerExecInspect_Call struct {
	*mock.Call
}

// ContainerExecInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - execID string
func (_e *ContainerAPIClient_Expecter) ContainerExecInspect(ctx interface{}, execID interface{}) *ContainerAPIClient_ContainerExecInspect_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecInspect_Call) Run(run func(ctx context.Context, execID string)) *ContainerAPIClient_ContainerExecInspect_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecInspect_Call) Return(_a0 container.ExecInspect, _a1 error) *ContainerAPIClient_ContainerExecInspect_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecInspect_Call) RunAndReturn(run func(context.Context, string) (container.ExecInspect, error)) *ContainerAPIClient_ContainerExecInspect_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerExecResize provides a mock function with given fields: ctx, execID, options
func (_m *ContainerAPIClient) ContainerExecResize(ctx context.Context, execID string, options container.ResizeOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerExecResize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerExecResize'
type ContainerAPIClient_ContainerExecResize_Call struct {
	*mock.Call
}

// ContainerExecResize is a helper method to define mock.On call
//   - ctx context.Context
//   - execID string
//   - options container.ResizeOptions
func (_e *ContainerAPIClient_Expecter) ContainerExecResize(ctx interface{}, execID interface{}, options interface{}) *ContainerAPIClient_ContainerExecResize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecResize_Call) Run(run func(ctx context.Context, execID string, options container.ResizeOptions)) *ContainerAPIClient_ContainerExecResize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecResize_Call) Return(_a0 error) *ContainerAPIClient_ContainerExecResize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecResize_Call) RunAndReturn(run func(context.Context, string, container.ResizeOptions) error) *ContainerAPIClient_ContainerExecResize_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerExecStart provides a mock function with given fields: ctx, execID, options
func (_m *ContainerAPIClient) ContainerExecStart(ctx context.Context, execID string, options container.ExecStartOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerExecStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerExecStart'
type ContainerAPIClient_ContainerExecStart_Call struct {
	*mock.Call
}

// ContainerExecStart is a helper method to define mock.On call
//   - ctx context.Context
//   - execID string
//   - options container.ExecStartOptions
func (_e *ContainerAPIClient_Expecter) ContainerExecStart(ctx interface{}, execID interface{}, options interface{}) *ContainerAPIClient_ContainerExecStart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecStart_Call) Run(run func(ctx context.Context, execID string, options container.ExecStartOptions)) *ContainerAPIClient_ContainerExecStart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecStart_Call) Return(_a0 error) *ContainerAPIClient_ContainerExecStart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExecStart_Call) RunAndReturn(run func(context.Context, string, container.ExecStartOptions) error) *ContainerAPIClient_ContainerExecStart_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerExport provides a mock function with given fields: ctx, _a1
func (_m *ContainerAPIClient) ContainerExport(ctx context.Context, _a1 string) (io.ReadCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser), nil
}

// ContainerAPIClient_ContainerExport_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerExport'
type ContainerAPIClient_ContainerExport_Call struct {
	*mock.Call
}

// ContainerExport is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
func (_e *ContainerAPIClient_Expecter) ContainerExport(ctx interface{}, _a1 interface{}) *ContainerAPIClient_ContainerExport_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExport_Call) Run(run func(ctx context.Context, _a1 string)) *ContainerAPIClient_ContainerExport_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExport_Call) Return(_a0 io.ReadCloser, _a1 error) *ContainerAPIClient_ContainerExport_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerExport_Call) RunAndReturn(run func(context.Context, string) (io.ReadCloser, error)) *ContainerAPIClient_ContainerExport_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerInspect provides a mock function with given fields: ctx, _a1
func (_m *ContainerAPIClient) ContainerInspect(ctx context.Context, _a1 string) (container.InspectResponse, error) {
	_ = "STUB: not implemented"
	return *new(container.InspectResponse), nil
}

// ContainerAPIClient_ContainerInspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspect'
type ContainerAPIClient_ContainerInspect_Call struct {
	*mock.Call
}

// ContainerInspect is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
func (_e *ContainerAPIClient_Expecter) ContainerInspect(ctx interface{}, _a1 interface{}) *ContainerAPIClient_ContainerInspect_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerInspect_Call) Run(run func(ctx context.Context, _a1 string)) *ContainerAPIClient_ContainerInspect_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerInspect_Call) Return(_a0 container.InspectResponse, _a1 error) *ContainerAPIClient_ContainerInspect_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerInspect_Call) RunAndReturn(run func(context.Context, string) (container.InspectResponse, error)) *ContainerAPIClient_ContainerInspect_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerInspectWithRaw provides a mock function with given fields: ctx, _a1, getSize
func (_m *ContainerAPIClient) ContainerInspectWithRaw(ctx context.Context, _a1 string, getSize bool) (container.InspectResponse, []byte, error) {
	_ = "STUB: not implemented"
	return *new(container.InspectResponse), nil, nil
}

// ContainerAPIClient_ContainerInspectWithRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerInspectWithRaw'
type ContainerAPIClient_ContainerInspectWithRaw_Call struct {
	*mock.Call
}

// ContainerInspectWithRaw is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - getSize bool
func (_e *ContainerAPIClient_Expecter) ContainerInspectWithRaw(ctx interface{}, _a1 interface{}, getSize interface{}) *ContainerAPIClient_ContainerInspectWithRaw_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerInspectWithRaw_Call) Run(run func(ctx context.Context, _a1 string, getSize bool)) *ContainerAPIClient_ContainerInspectWithRaw_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerInspectWithRaw_Call) Return(_a0 container.InspectResponse, _a1 []byte, _a2 error) *ContainerAPIClient_ContainerInspectWithRaw_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerInspectWithRaw_Call) RunAndReturn(run func(context.Context, string, bool) (container.InspectResponse, []byte, error)) *ContainerAPIClient_ContainerInspectWithRaw_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerKill provides a mock function with given fields: ctx, _a1, signal
func (_m *ContainerAPIClient) ContainerKill(ctx context.Context, _a1 string, signal string) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerKill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerKill'
type ContainerAPIClient_ContainerKill_Call struct {
	*mock.Call
}

// ContainerKill is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - signal string
func (_e *ContainerAPIClient_Expecter) ContainerKill(ctx interface{}, _a1 interface{}, signal interface{}) *ContainerAPIClient_ContainerKill_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerKill_Call) Run(run func(ctx context.Context, _a1 string, signal string)) *ContainerAPIClient_ContainerKill_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerKill_Call) Return(_a0 error) *ContainerAPIClient_ContainerKill_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerKill_Call) RunAndReturn(run func(context.Context, string, string) error) *ContainerAPIClient_ContainerKill_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerList provides a mock function with given fields: ctx, options
func (_m *ContainerAPIClient) ContainerList(ctx context.Context, options container.ListOptions) ([]container.Summary, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ContainerAPIClient_ContainerList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerList'
type ContainerAPIClient_ContainerList_Call struct {
	*mock.Call
}

// ContainerList is a helper method to define mock.On call
//   - ctx context.Context
//   - options container.ListOptions
func (_e *ContainerAPIClient_Expecter) ContainerList(ctx interface{}, options interface{}) *ContainerAPIClient_ContainerList_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerList_Call) Run(run func(ctx context.Context, options container.ListOptions)) *ContainerAPIClient_ContainerList_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerList_Call) Return(_a0 []container.Summary, _a1 error) *ContainerAPIClient_ContainerList_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerList_Call) RunAndReturn(run func(context.Context, container.ListOptions) ([]container.Summary, error)) *ContainerAPIClient_ContainerList_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerLogs provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerLogs(ctx context.Context, _a1 string, options container.LogsOptions) (io.ReadCloser, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser), nil
}

// ContainerAPIClient_ContainerLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerLogs'
type ContainerAPIClient_ContainerLogs_Call struct {
	*mock.Call
}

// ContainerLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.LogsOptions
func (_e *ContainerAPIClient_Expecter) ContainerLogs(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerLogs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerLogs_Call) Run(run func(ctx context.Context, _a1 string, options container.LogsOptions)) *ContainerAPIClient_ContainerLogs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerLogs_Call) Return(_a0 io.ReadCloser, _a1 error) *ContainerAPIClient_ContainerLogs_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerLogs_Call) RunAndReturn(run func(context.Context, string, container.LogsOptions) (io.ReadCloser, error)) *ContainerAPIClient_ContainerLogs_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerPause provides a mock function with given fields: ctx, _a1
func (_m *ContainerAPIClient) ContainerPause(ctx context.Context, _a1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerPause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerPause'
type ContainerAPIClient_ContainerPause_Call struct {
	*mock.Call
}

// ContainerPause is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
func (_e *ContainerAPIClient_Expecter) ContainerPause(ctx interface{}, _a1 interface{}) *ContainerAPIClient_ContainerPause_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerPause_Call) Run(run func(ctx context.Context, _a1 string)) *ContainerAPIClient_ContainerPause_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerPause_Call) Return(_a0 error) *ContainerAPIClient_ContainerPause_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerPause_Call) RunAndReturn(run func(context.Context, string) error) *ContainerAPIClient_ContainerPause_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerRemove provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerRemove(ctx context.Context, _a1 string, options container.RemoveOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerRemove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRemove'
type ContainerAPIClient_ContainerRemove_Call struct {
	*mock.Call
}

// ContainerRemove is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.RemoveOptions
func (_e *ContainerAPIClient_Expecter) ContainerRemove(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerRemove_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRemove_Call) Run(run func(ctx context.Context, _a1 string, options container.RemoveOptions)) *ContainerAPIClient_ContainerRemove_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRemove_Call) Return(_a0 error) *ContainerAPIClient_ContainerRemove_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRemove_Call) RunAndReturn(run func(context.Context, string, container.RemoveOptions) error) *ContainerAPIClient_ContainerRemove_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerRename provides a mock function with given fields: ctx, _a1, newContainerName
func (_m *ContainerAPIClient) ContainerRename(ctx context.Context, _a1 string, newContainerName string) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerRename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRename'
type ContainerAPIClient_ContainerRename_Call struct {
	*mock.Call
}

// ContainerRename is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - newContainerName string
func (_e *ContainerAPIClient_Expecter) ContainerRename(ctx interface{}, _a1 interface{}, newContainerName interface{}) *ContainerAPIClient_ContainerRename_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRename_Call) Run(run func(ctx context.Context, _a1 string, newContainerName string)) *ContainerAPIClient_ContainerRename_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRename_Call) Return(_a0 error) *ContainerAPIClient_ContainerRename_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRename_Call) RunAndReturn(run func(context.Context, string, string) error) *ContainerAPIClient_ContainerRename_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerResize provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerResize(ctx context.Context, _a1 string, options container.ResizeOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerResize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerResize'
type ContainerAPIClient_ContainerResize_Call struct {
	*mock.Call
}

// ContainerResize is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.ResizeOptions
func (_e *ContainerAPIClient_Expecter) ContainerResize(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerResize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerResize_Call) Run(run func(ctx context.Context, _a1 string, options container.ResizeOptions)) *ContainerAPIClient_ContainerResize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerResize_Call) Return(_a0 error) *ContainerAPIClient_ContainerResize_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerResize_Call) RunAndReturn(run func(context.Context, string, container.ResizeOptions) error) *ContainerAPIClient_ContainerResize_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerRestart provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerRestart(ctx context.Context, _a1 string, options container.StopOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerRestart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerRestart'
type ContainerAPIClient_ContainerRestart_Call struct {
	*mock.Call
}

// ContainerRestart is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.StopOptions
func (_e *ContainerAPIClient_Expecter) ContainerRestart(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerRestart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRestart_Call) Run(run func(ctx context.Context, _a1 string, options container.StopOptions)) *ContainerAPIClient_ContainerRestart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRestart_Call) Return(_a0 error) *ContainerAPIClient_ContainerRestart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerRestart_Call) RunAndReturn(run func(context.Context, string, container.StopOptions) error) *ContainerAPIClient_ContainerRestart_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStart provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerStart(ctx context.Context, _a1 string, options container.StartOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerStart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStart'
type ContainerAPIClient_ContainerStart_Call struct {
	*mock.Call
}

// ContainerStart is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.StartOptions
func (_e *ContainerAPIClient_Expecter) ContainerStart(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerStart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStart_Call) Run(run func(ctx context.Context, _a1 string, options container.StartOptions)) *ContainerAPIClient_ContainerStart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStart_Call) Return(_a0 error) *ContainerAPIClient_ContainerStart_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStart_Call) RunAndReturn(run func(context.Context, string, container.StartOptions) error) *ContainerAPIClient_ContainerStart_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStatPath provides a mock function with given fields: ctx, _a1, path
func (_m *ContainerAPIClient) ContainerStatPath(ctx context.Context, _a1 string, path string) (container.PathStat, error) {
	_ = "STUB: not implemented"
	return *new(container.PathStat), nil
}

// ContainerAPIClient_ContainerStatPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStatPath'
type ContainerAPIClient_ContainerStatPath_Call struct {
	*mock.Call
}

// ContainerStatPath is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - path string
func (_e *ContainerAPIClient_Expecter) ContainerStatPath(ctx interface{}, _a1 interface{}, path interface{}) *ContainerAPIClient_ContainerStatPath_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStatPath_Call) Run(run func(ctx context.Context, _a1 string, path string)) *ContainerAPIClient_ContainerStatPath_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStatPath_Call) Return(_a0 container.PathStat, _a1 error) *ContainerAPIClient_ContainerStatPath_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStatPath_Call) RunAndReturn(run func(context.Context, string, string) (container.PathStat, error)) *ContainerAPIClient_ContainerStatPath_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStats provides a mock function with given fields: ctx, _a1, stream
func (_m *ContainerAPIClient) ContainerStats(ctx context.Context, _a1 string, stream bool) (container.StatsResponseReader, error) {
	_ = "STUB: not implemented"
	return *new(container.StatsResponseReader), nil
}

// ContainerAPIClient_ContainerStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStats'
type ContainerAPIClient_ContainerStats_Call struct {
	*mock.Call
}

// ContainerStats is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - stream bool
func (_e *ContainerAPIClient_Expecter) ContainerStats(ctx interface{}, _a1 interface{}, stream interface{}) *ContainerAPIClient_ContainerStats_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStats_Call) Run(run func(ctx context.Context, _a1 string, stream bool)) *ContainerAPIClient_ContainerStats_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStats_Call) Return(_a0 container.StatsResponseReader, _a1 error) *ContainerAPIClient_ContainerStats_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStats_Call) RunAndReturn(run func(context.Context, string, bool) (container.StatsResponseReader, error)) *ContainerAPIClient_ContainerStats_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStatsOneShot provides a mock function with given fields: ctx, _a1
func (_m *ContainerAPIClient) ContainerStatsOneShot(ctx context.Context, _a1 string) (container.StatsResponseReader, error) {
	_ = "STUB: not implemented"
	return *new(container.StatsResponseReader), nil
}

// ContainerAPIClient_ContainerStatsOneShot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStatsOneShot'
type ContainerAPIClient_ContainerStatsOneShot_Call struct {
	*mock.Call
}

// ContainerStatsOneShot is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
func (_e *ContainerAPIClient_Expecter) ContainerStatsOneShot(ctx interface{}, _a1 interface{}) *ContainerAPIClient_ContainerStatsOneShot_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStatsOneShot_Call) Run(run func(ctx context.Context, _a1 string)) *ContainerAPIClient_ContainerStatsOneShot_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStatsOneShot_Call) Return(_a0 container.StatsResponseReader, _a1 error) *ContainerAPIClient_ContainerStatsOneShot_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStatsOneShot_Call) RunAndReturn(run func(context.Context, string) (container.StatsResponseReader, error)) *ContainerAPIClient_ContainerStatsOneShot_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerStop provides a mock function with given fields: ctx, _a1, options
func (_m *ContainerAPIClient) ContainerStop(ctx context.Context, _a1 string, options container.StopOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerStop'
type ContainerAPIClient_ContainerStop_Call struct {
	*mock.Call
}

// ContainerStop is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - options container.StopOptions
func (_e *ContainerAPIClient_Expecter) ContainerStop(ctx interface{}, _a1 interface{}, options interface{}) *ContainerAPIClient_ContainerStop_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStop_Call) Run(run func(ctx context.Context, _a1 string, options container.StopOptions)) *ContainerAPIClient_ContainerStop_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStop_Call) Return(_a0 error) *ContainerAPIClient_ContainerStop_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerStop_Call) RunAndReturn(run func(context.Context, string, container.StopOptions) error) *ContainerAPIClient_ContainerStop_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerTop provides a mock function with given fields: ctx, _a1, arguments
func (_m *ContainerAPIClient) ContainerTop(ctx context.Context, _a1 string, arguments []string) (container.TopResponse, error) {
	_ = "STUB: not implemented"
	return *new(container.TopResponse), nil
}

// ContainerAPIClient_ContainerTop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerTop'
type ContainerAPIClient_ContainerTop_Call struct {
	*mock.Call
}

// ContainerTop is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - arguments []string
func (_e *ContainerAPIClient_Expecter) ContainerTop(ctx interface{}, _a1 interface{}, arguments interface{}) *ContainerAPIClient_ContainerTop_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerTop_Call) Run(run func(ctx context.Context, _a1 string, arguments []string)) *ContainerAPIClient_ContainerTop_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerTop_Call) Return(_a0 container.TopResponse, _a1 error) *ContainerAPIClient_ContainerTop_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerTop_Call) RunAndReturn(run func(context.Context, string, []string) (container.TopResponse, error)) *ContainerAPIClient_ContainerTop_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerUnpause provides a mock function with given fields: ctx, _a1
func (_m *ContainerAPIClient) ContainerUnpause(ctx context.Context, _a1 string) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_ContainerUnpause_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerUnpause'
type ContainerAPIClient_ContainerUnpause_Call struct {
	*mock.Call
}

// ContainerUnpause is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
func (_e *ContainerAPIClient_Expecter) ContainerUnpause(ctx interface{}, _a1 interface{}) *ContainerAPIClient_ContainerUnpause_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerUnpause_Call) Run(run func(ctx context.Context, _a1 string)) *ContainerAPIClient_ContainerUnpause_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerUnpause_Call) Return(_a0 error) *ContainerAPIClient_ContainerUnpause_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerUnpause_Call) RunAndReturn(run func(context.Context, string) error) *ContainerAPIClient_ContainerUnpause_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerUpdate provides a mock function with given fields: ctx, _a1, updateConfig
func (_m *ContainerAPIClient) ContainerUpdate(ctx context.Context, _a1 string, updateConfig container.UpdateConfig) (container.UpdateResponse, error) {
	_ = "STUB: not implemented"
	return *new(container.UpdateResponse), nil
}

// ContainerAPIClient_ContainerUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerUpdate'
type ContainerAPIClient_ContainerUpdate_Call struct {
	*mock.Call
}

// ContainerUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - updateConfig container.UpdateConfig
func (_e *ContainerAPIClient_Expecter) ContainerUpdate(ctx interface{}, _a1 interface{}, updateConfig interface{}) *ContainerAPIClient_ContainerUpdate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerUpdate_Call) Run(run func(ctx context.Context, _a1 string, updateConfig container.UpdateConfig)) *ContainerAPIClient_ContainerUpdate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerUpdate_Call) Return(_a0 container.UpdateResponse, _a1 error) *ContainerAPIClient_ContainerUpdate_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerUpdate_Call) RunAndReturn(run func(context.Context, string, container.UpdateConfig) (container.UpdateResponse, error)) *ContainerAPIClient_ContainerUpdate_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainerWait provides a mock function with given fields: ctx, _a1, condition
func (_m *ContainerAPIClient) ContainerWait(ctx context.Context, _a1 string, condition container.WaitCondition) (<-chan container.WaitResponse, <-chan error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ContainerAPIClient_ContainerWait_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainerWait'
type ContainerAPIClient_ContainerWait_Call struct {
	*mock.Call
}

// ContainerWait is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - condition container.WaitCondition
func (_e *ContainerAPIClient_Expecter) ContainerWait(ctx interface{}, _a1 interface{}, condition interface{}) *ContainerAPIClient_ContainerWait_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerWait_Call) Run(run func(ctx context.Context, _a1 string, condition container.WaitCondition)) *ContainerAPIClient_ContainerWait_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerWait_Call) Return(_a0 <-chan container.WaitResponse, _a1 <-chan error) *ContainerAPIClient_ContainerWait_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainerWait_Call) RunAndReturn(run func(context.Context, string, container.WaitCondition) (<-chan container.WaitResponse, <-chan error)) *ContainerAPIClient_ContainerWait_Call {
	_ = "STUB: not implemented"
	return nil
}

// ContainersPrune provides a mock function with given fields: ctx, pruneFilters
func (_m *ContainerAPIClient) ContainersPrune(ctx context.Context, pruneFilters filters.Args) (container.PruneReport, error) {
	_ = "STUB: not implemented"
	return *new(container.PruneReport), nil
}

// ContainerAPIClient_ContainersPrune_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContainersPrune'
type ContainerAPIClient_ContainersPrune_Call struct {
	*mock.Call
}

// ContainersPrune is a helper method to define mock.On call
//   - ctx context.Context
//   - pruneFilters filters.Args
func (_e *ContainerAPIClient_Expecter) ContainersPrune(ctx interface{}, pruneFilters interface{}) *ContainerAPIClient_ContainersPrune_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainersPrune_Call) Run(run func(ctx context.Context, pruneFilters filters.Args)) *ContainerAPIClient_ContainersPrune_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainersPrune_Call) Return(_a0 container.PruneReport, _a1 error) *ContainerAPIClient_ContainersPrune_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_ContainersPrune_Call) RunAndReturn(run func(context.Context, filters.Args) (container.PruneReport, error)) *ContainerAPIClient_ContainersPrune_Call {
	_ = "STUB: not implemented"
	return nil
}

// CopyFromContainer provides a mock function with given fields: ctx, _a1, srcPath
func (_m *ContainerAPIClient) CopyFromContainer(ctx context.Context, _a1 string, srcPath string) (io.ReadCloser, container.PathStat, error) {
	_ = "STUB: not implemented"
	return *new(io.ReadCloser), *new(container.PathStat), nil
}

// ContainerAPIClient_CopyFromContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyFromContainer'
type ContainerAPIClient_CopyFromContainer_Call struct {
	*mock.Call
}

// CopyFromContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - srcPath string
func (_e *ContainerAPIClient_Expecter) CopyFromContainer(ctx interface{}, _a1 interface{}, srcPath interface{}) *ContainerAPIClient_CopyFromContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_CopyFromContainer_Call) Run(run func(ctx context.Context, _a1 string, srcPath string)) *ContainerAPIClient_CopyFromContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_CopyFromContainer_Call) Return(_a0 io.ReadCloser, _a1 container.PathStat, _a2 error) *ContainerAPIClient_CopyFromContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_CopyFromContainer_Call) RunAndReturn(run func(context.Context, string, string) (io.ReadCloser, container.PathStat, error)) *ContainerAPIClient_CopyFromContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// CopyToContainer provides a mock function with given fields: ctx, _a1, path, content, options
func (_m *ContainerAPIClient) CopyToContainer(ctx context.Context, _a1 string, path string, content io.Reader, options container.CopyToContainerOptions) error {
	_ = "STUB: not implemented"
	return nil
}

// ContainerAPIClient_CopyToContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyToContainer'
type ContainerAPIClient_CopyToContainer_Call struct {
	*mock.Call
}

// CopyToContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 string
//   - path string
//   - content io.Reader
//   - options container.CopyToContainerOptions
func (_e *ContainerAPIClient_Expecter) CopyToContainer(ctx interface{}, _a1 interface{}, path interface{}, content interface{}, options interface{}) *ContainerAPIClient_CopyToContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_CopyToContainer_Call) Run(run func(ctx context.Context, _a1 string, path string, content io.Reader, options container.CopyToContainerOptions)) *ContainerAPIClient_CopyToContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_CopyToContainer_Call) Return(_a0 error) *ContainerAPIClient_CopyToContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *ContainerAPIClient_CopyToContainer_Call) RunAndReturn(run func(context.Context, string, string, io.Reader, container.CopyToContainerOptions) error) *ContainerAPIClient_CopyToContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewContainerAPIClient creates a new instance of ContainerAPIClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContainerAPIClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContainerAPIClient {
	_ = "STUB: not implemented"
	return nil
}
