// Code generated by mockery. DO NOT EDIT.

package containerd

import (
	context "context"

	client "github.com/containerd/containerd/v2/client"

	mock "github.com/stretchr/testify/mock"
)

// MockapiClient is an autogenerated mock type for the apiClient type
type MockapiClient struct {
	mock.Mock
}

type MockapiClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockapiClient) EXPECT() *MockapiClient_Expecter { _ = "STUB: not implemented"; return nil }

// Close provides a mock function with no fields
func (_m *MockapiClient) Close() error { _ = "STUB: not implemented"; return nil }

// MockapiClient_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockapiClient_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockapiClient_Expecter) Close() *MockapiClient_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Close_Call) Run(run func()) *MockapiClient_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Close_Call) Return(_a0 error) *MockapiClient_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Close_Call) RunAndReturn(run func() error) *MockapiClient_Close_Call {
	_ = "STUB: not implemented"
	return nil
}

// Containers provides a mock function with given fields: ctx, filters
func (_m *MockapiClient) Containers(ctx context.Context, filters ...string) ([]client.Container, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// MockapiClient_Containers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Containers'
type MockapiClient_Containers_Call struct {
	*mock.Call
}

// Containers is a helper method to define mock.On call
//   - ctx context.Context
//   - filters ...string
func (_e *MockapiClient_Expecter) Containers(ctx interface{}, filters ...interface{}) *MockapiClient_Containers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Containers_Call) Run(run func(ctx context.Context, filters ...string)) *MockapiClient_Containers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Containers_Call) Return(_a0 []client.Container, _a1 error) *MockapiClient_Containers_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Containers_Call) RunAndReturn(run func(context.Context, ...string) ([]client.Container, error)) *MockapiClient_Containers_Call {
	_ = "STUB: not implemented"
	return nil
}

// GetImage provides a mock function with given fields: ctx, ref
func (_m *MockapiClient) GetImage(ctx context.Context, ref string) (client.Image, error) {
	_ = "STUB: not implemented"
	return *new(client.Image), nil
}

// MockapiClient_GetImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImage'
type MockapiClient_GetImage_Call struct {
	*mock.Call
}

// GetImage is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
func (_e *MockapiClient_Expecter) GetImage(ctx interface{}, ref interface{}) *MockapiClient_GetImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_GetImage_Call) Run(run func(ctx context.Context, ref string)) *MockapiClient_GetImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_GetImage_Call) Return(_a0 client.Image, _a1 error) *MockapiClient_GetImage_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_GetImage_Call) RunAndReturn(run func(context.Context, string) (client.Image, error)) *MockapiClient_GetImage_Call {
	_ = "STUB: not implemented"
	return nil
}

// LoadContainer provides a mock function with given fields: ctx, id
func (_m *MockapiClient) LoadContainer(ctx context.Context, id string) (client.Container, error) {
	_ = "STUB: not implemented"
	return *new(client.Container), nil
}

// MockapiClient_LoadContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadContainer'
type MockapiClient_LoadContainer_Call struct {
	*mock.Call
}

// LoadContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockapiClient_Expecter) LoadContainer(ctx interface{}, id interface{}) *MockapiClient_LoadContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_LoadContainer_Call) Run(run func(ctx context.Context, id string)) *MockapiClient_LoadContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_LoadContainer_Call) Return(_a0 client.Container, _a1 error) *MockapiClient_LoadContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_LoadContainer_Call) RunAndReturn(run func(context.Context, string) (client.Container, error)) *MockapiClient_LoadContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewContainer provides a mock function with given fields: ctx, id, opts
func (_m *MockapiClient) NewContainer(ctx context.Context, id string, opts ...client.NewContainerOpts) (client.Container, error) {
	_ = "STUB: not implemented"
	return *new(client.Container), nil
}

// MockapiClient_NewContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewContainer'
type MockapiClient_NewContainer_Call struct {
	*mock.Call
}

// NewContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts ...client.NewContainerOpts
func (_e *MockapiClient_Expecter) NewContainer(ctx interface{}, id interface{}, opts ...interface{}) *MockapiClient_NewContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_NewContainer_Call) Run(run func(ctx context.Context, id string, opts ...client.NewContainerOpts)) *MockapiClient_NewContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_NewContainer_Call) Return(_a0 client.Container, _a1 error) *MockapiClient_NewContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_NewContainer_Call) RunAndReturn(run func(context.Context, string, ...client.NewContainerOpts) (client.Container, error)) *MockapiClient_NewContainer_Call {
	_ = "STUB: not implemented"
	return nil
}

// Pull provides a mock function with given fields: ctx, ref, opts
func (_m *MockapiClient) Pull(ctx context.Context, ref string, opts ...client.RemoteOpt) (client.Image, error) {
	_ = "STUB: not implemented"
	return *new(client.Image), nil
}

// MockapiClient_Pull_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pull'
type MockapiClient_Pull_Call struct {
	*mock.Call
}

// Pull is a helper method to define mock.On call
//   - ctx context.Context
//   - ref string
//   - opts ...client.RemoteOpt
func (_e *MockapiClient_Expecter) Pull(ctx interface{}, ref interface{}, opts ...interface{}) *MockapiClient_Pull_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Pull_Call) Run(run func(ctx context.Context, ref string, opts ...client.RemoteOpt)) *MockapiClient_Pull_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Pull_Call) Return(_a0 client.Image, _a1 error) *MockapiClient_Pull_Call {
	_ = "STUB: not implemented"
	return nil
}

func (_c *MockapiClient_Pull_Call) RunAndReturn(run func(context.Context, string, ...client.RemoteOpt) (client.Image, error)) *MockapiClient_Pull_Call {
	_ = "STUB: not implemented"
	return nil
}

// NewMockapiClient creates a new instance of MockapiClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockapiClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockapiClient {
	_ = "STUB: not implemented"
	return nil
}
